name: Node CI

on:
  push:
    branches: [ master ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '30 1 15 * *'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}


jobs:
  node:
    name: Node image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Log in to Coding
        uses: docker/login-action@v3
        with:
          registry: fucksky-docker.pkg.coding.net
          username: ${{ secrets.CODING_USERNAME }}
          password: ${{ secrets.CODING_PASSWORD }}
      - name: 16
        uses: docker/build-push-action@v5
        with:
          context: .
          file: node/16/Dockerfile
          push: true
          tags: |
            buzzxu/docker-ci:node-16
            ghcr.io/buzzxu/docker-ci:node-16
            fucksky-docker.pkg.coding.net/yuanmai/docker/docker-ci:node-16
      - name: 18
        uses: docker/build-push-action@v5
        with:
          context: .
          file: node/18/Dockerfile
          push: true
          tags: |
            buzzxu/docker-ci:node-18
            ghcr.io/buzzxu/docker-ci:node-18
            fucksky-docker.pkg.coding.net/yuanmai/docker/docker-ci:node-18
      - name: 19
        uses: docker/build-push-action@v5
        with:
          context: .
          file: node/19/Dockerfile
          push: true
          tags: |
            buzzxu/docker-ci:node-19
            ghcr.io/buzzxu/docker-ci:node-19
            fucksky-docker.pkg.coding.net/yuanmai/docker/docker-ci:node-19
      - name: 20
        uses: docker/build-push-action@v5
        with:
          context: .
          file: node/20/Dockerfile
          push: true
          tags: |
            buzzxu/docker-ci:node-20
            ghcr.io/buzzxu/docker-ci:node-20
            fucksky-docker.pkg.coding.net/yuanmai/docker/docker-ci:node-20
      - name: latest
        uses: docker/build-push-action@v5
        with:
          context: .
          file: node/latest/Dockerfile
          push: true
          tags: |
            buzzxu/docker-ci:node
            ghcr.io/buzzxu/docker-ci:node
            fucksky-docker.pkg.coding.net/yuanmai/docker/docker-ci:node
            buzzxu/docker-ci:node-22
            ghcr.io/buzzxu/docker-ci:node-22
            fucksky-docker.pkg.coding.net/yuanmai/docker/docker-ci:node-22