name: Docker

on:
  push:
    branches: [ master ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '30 1 15 * *'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}


jobs:
  stable:
    name: Stable image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            buzzxu/docker-ci:stable
  java:
    needs: stable
    name: Java image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: 17
        uses: docker/build-push-action@v2
        with:
          context: .
          file: java/17/Dockerfile
          push: true
          tags: |
            buzzxu/docker-ci:java
            ghcr.io/buzzxu/docker-ci:java
            buzzxu/docker-ci:java-17
            ghcr.io/buzzxu/docker-ci:java-17
      - name: 20
        uses: docker/build-push-action@v2
        with:
          context: .
          file: java/20/Dockerfile
          push: true
          tags: |
            buzzxu/docker-ci:java-20
            ghcr.io/buzzxu/docker-ci:java-20
  maven:
    needs: java
    name: Maven image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: 17
        uses: docker/build-push-action@v2
        with:
          context: .
          file: maven/17/Dockerfile
          push: true
          tags: |
            buzzxu/docker-ci:maven
            ghcr.io/buzzxu/docker-ci:maven
            buzzxu/docker-ci:maven-17
            ghcr.io/buzzxu/docker-ci:maven-17
      - name: 20
        uses: docker/build-push-action@v2
        with:
          context: .
          file: maven/20/Dockerfile
          push: true
          tags: |
            buzzxu/docker-ci:maven-20
            ghcr.io/buzzxu/docker-ci:maven-20
  gradle:
    needs: java
    name: Gradle image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: 17
        uses: docker/build-push-action@v2
        with:
          context: .
          file: gradle/17/Dockerfile
          push: true
          tags: |
            buzzxu/docker-ci:gradle
            ghcr.io/buzzxu/docker-ci:gradle
            buzzxu/docker-ci:gradle-17
            ghcr.io/buzzxu/docker-ci:gradle-17
