name: Docker Node

on:
  push:
    branches: [ master ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '30 1 15 * *'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}


jobs:
  node:
    name: Node image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: 16
        uses: docker/build-push-action@v2
        with:
          context: .
          file: node/16/Dockerfile
          push: true
          tags: |
            buzzxu/docker-ci:node
            ghcr.io/buzzxu/docker-ci:node
            buzzxu/docker-ci:node-16
            ghcr.io/buzzxu/docker-ci:node-16
      - name: 18
        uses: docker/build-push-action@v2
        with:
          context: .
          file: node/18/Dockerfile
          push: true
          tags: |
            buzzxu/docker-ci:node-18
            ghcr.io/buzzxu/docker-ci:node-18
      - name: 19
        uses: docker/build-push-action@v2
        with:
          context: .
          file: node/19/Dockerfile
          push: true
          tags: |
            buzzxu/docker-ci:node-19
            ghcr.io/buzzxu/docker-ci:node-19
      - name: 20
        uses: docker/build-push-action@v2
        with:
          context: .
          file: node/20/Dockerfile
          push: true
          tags: |
            buzzxu/docker-ci:node-20
            ghcr.io/buzzxu/docker-ci:node-20
  node-taro:
    needs: node
    name: Node taro
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: 16
        uses: docker/build-push-action@v2
        with:
          context: .
          file: node/16/taro/Dockerfile
          push: true
          tags: |
            buzzxu/docker-ci:node-taro
            ghcr.io/buzzxu/docker-ci:node-taro
            buzzxu/docker-ci:node-taro-16
            ghcr.io/buzzxu/docker-ci:node-taro-16
      - name: 18
        uses: docker/build-push-action@v2
        with:
          context: .
          file: node/18/taro/Dockerfile
          push: true
          tags: |
            buzzxu/docker-ci:node-taro-18
            ghcr.io/buzzxu/docker-ci:node-taro-18
      - name: 19
        uses: docker/build-push-action@v2
        with:
          context: .
          file: node/19/taro/Dockerfile
          push: true
          tags: |
            buzzxu/docker-ci:node-taro-19
            ghcr.io/buzzxu/docker-ci:node-taro-19
      - name: 20
        uses: docker/build-push-action@v2
        with:
          context: .
          file: node/20/taro/Dockerfile
          push: true
          tags: |
            buzzxu/docker-ci:node-taro-20
            ghcr.io/buzzxu/docker-ci:node-taro-20
