name: Node Coding

on:
  push:
    branches: [ master ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '30 1 15 * *'


jobs:
  node:
    name: Node image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: node-16
        id: node-16
        uses: risfeng/docker-image-build-push-action@v1.0
        with:
          registry_url: 'fucksky-docker.pkg.coding.net'
          namespaces: 'fucksky-docker.pkg.coding.net/yuanmai/docker'
          repository_name: 'docker-ci'
          user_name: ${{ secrets.CODING_USERNAME }}
          password: ${{ secrets.CODING_PASSWORD }}
          docker_file: 'node/16'
          image_version: 'node'
      - name: node-18
        id: node-18
        uses: risfeng/docker-image-build-push-action@v1.0
        with:
          registry_url: 'fucksky-docker.pkg.coding.net'
          namespaces: 'fucksky-docker.pkg.coding.net/yuanmai/docker'
          repository_name: 'docker-ci'
          user_name: ${{ secrets.CODING_USERNAME }}
          password: ${{ secrets.CODING_PASSWORD }}
          docker_file: 'node/18'
          image_version: 'node-18'
      - name: node-19
        id: node-19
        uses: risfeng/docker-image-build-push-action@v1.0
        with:
          registry_url: 'fucksky-docker.pkg.coding.net'
          namespaces: 'fucksky-docker.pkg.coding.net/yuanmai/docker'
          repository_name: 'docker-ci'
          user_name: ${{ secrets.CODING_USERNAME }}
          password: ${{ secrets.CODING_PASSWORD }}
          docker_file: 'node/19'
          image_version: 'node-19'
      - name: node-20
        id: node-20
        uses: risfeng/docker-image-build-push-action@v1.0
        with:
          registry_url: 'fucksky-docker.pkg.coding.net'
          namespaces: 'fucksky-docker.pkg.coding.net/yuanmai/docker'
          repository_name: 'docker-ci'
          user_name: ${{ secrets.CODING_USERNAME }}
          password: ${{ secrets.CODING_PASSWORD }}
          docker_file: 'node/20'
          image_version: 'node-20'
      - name: node-latest
        id: node-latest
        uses: risfeng/docker-image-build-push-action@v1.0
        with:
          registry_url: 'fucksky-docker.pkg.coding.net'
          namespaces: 'fucksky-docker.pkg.coding.net/yuanmai/docker'
          repository_name: 'docker-ci'
          user_name: ${{ secrets.CODING_USERNAME }}
          password: ${{ secrets.CODING_PASSWORD }}
          docker_file: 'node/latest'
          image_version: 'node-latest'
  node-taro:
    needs: node
    name: Node taro
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: node-taro-16
        id: node-taro-16
        uses: risfeng/docker-image-build-push-action@v1.0
        with:
          registry_url: 'fucksky-docker.pkg.coding.net'
          namespaces: 'fucksky-docker.pkg.coding.net/yuanmai/docker'
          repository_name: 'docker-ci'
          user_name: ${{ secrets.CODING_USERNAME }}
          password: ${{ secrets.CODING_PASSWORD }}
          docker_file: 'node/16/taro'
          image_version: 'node-taro-16'
      - name: node-taro-18
        id: node-taro-18
        uses: risfeng/docker-image-build-push-action@v1.0
        with:
          registry_url: 'fucksky-docker.pkg.coding.net'
          namespaces: 'fucksky-docker.pkg.coding.net/yuanmai/docker'
          repository_name: 'docker-ci'
          user_name: ${{ secrets.CODING_USERNAME }}
          password: ${{ secrets.CODING_PASSWORD }}
          docker_file: 'node/18/taro'
          image_version: 'node-taro-18'
      - name: node-taro-19
        id: node-taro-19
        uses: risfeng/docker-image-build-push-action@v1.0
        with:
          registry_url: 'fucksky-docker.pkg.coding.net'
          namespaces: 'fucksky-docker.pkg.coding.net/yuanmai/docker'
          repository_name: 'docker-ci'
          user_name: ${{ secrets.CODING_USERNAME }}
          password: ${{ secrets.CODING_PASSWORD }}
          docker_file: 'node/19/taro'
          image_version: 'node-taro-19'
      - name: node-taro-20
        id: node-taro-20
        uses: risfeng/docker-image-build-push-action@v1.0
        with:
          registry_url: 'fucksky-docker.pkg.coding.net'
          namespaces: 'fucksky-docker.pkg.coding.net/yuanmai/docker'
          repository_name: 'docker-ci'
          user_name: ${{ secrets.CODING_USERNAME }}
          password: ${{ secrets.CODING_PASSWORD }}
          docker_file: 'node/20/taro'
          image_version: 'node-taro-20'
      - name: node-taro-latest
        id: node-taro-latest
        uses: risfeng/docker-image-build-push-action@v1.0
        with:
          registry_url: 'fucksky-docker.pkg.coding.net'
          namespaces: 'fucksky-docker.pkg.coding.net/yuanmai/docker'
          repository_name: 'docker-ci'
          user_name: ${{ secrets.CODING_USERNAME }}
          password: ${{ secrets.CODING_PASSWORD }}
          docker_file: 'node/latest/taro'
          image_version: 'node-taro-latest'
